export const KNOWN_INFUSION_MAPPING_CREATE = 'serviceData.KNOWN_INFUSION_MAPPING_CREATE' as const;
export const KNOWN_INFUSION_MAPPING_DESTROY = 'serviceData.KNOWN_INFUSION_MAPPING_DESTROY' as const;
export const KNOWN_INFUSION_MAPPING_ADD = 'serviceData.KNOWN_INFUSION_MAPPING_ADD' as const;
export const KNOWN_INFUSION_MAPPING_ADD_COMMIT = 'serviceData.KNOWN_INFUSION_MAPPING_ADD_COMMIT' as const;
export const KNOWN_INFUSION_MAPPING_SET = 'serviceData.KNOWN_INFUSION_MAPPING_SET' as const;
export const KNOWN_INFUSION_MAPPING_SET_COMMIT = 'serviceData.KNOWN_INFUSION_MAPPING_SET_COMMIT' as const;
export const KNOWN_INFUSION_MAPPING_REMOVE = 'serviceData.KNOWN_INFUSION_MAPPING_REMOVE' as const;
export const KNOWN_INFUSION_MAPPING_REMOVE_COMMIT = 'serviceData.KNOWN_INFUSION_MAPPING_REMOVE_COMMIT' as const;