export const VEHICLE_COMPONENT_MAPPING_ADD = 'serviceData.VEHICLE_COMPONENT_MAPPING_ADD' as const;
export const VEHICLE_COMPONENT_MAPPING_ADD_COMMIT = 'serviceData.VEHICLE_COMPONENT_MAPPING_ADD_COMMIT' as const;
export const VEHICLE_COMPONENT_MAPPING_REMOVE = 'serviceData.VEHICLE_COMPONENT_MAPPING_REMOVE' as const;
export const VEHICLE_COMPONENT_MAPPING_REMOVE_COMMIT = 'serviceData.VEHICLE_COMPONENT_MAPPING_REMOVE_COMMIT' as const;
export const VEHICLE_COMPONENT_MAPPING_HIT_POINTS_SET = 'serviceData.VEHICLE_COMPONENT_MAPPING_HIT_POINTS_SET' as const;
export const VEHICLE_COMPONENT_MAPPING_HIT_POINTS_SET_COMMIT = 'serviceData.VEHICLE_COMPONENT_MAPPING_HIT_POINTS_SET_COMMIT' as const;